#!/usr/bin/env python3
"""Resolve reviewed direct pins into portable, hash-verified wheel-only locks.

Run explicitly when updating dependencies. Resolution uses public PyPI and never
executes source distributions. Generated files are replaced only after every
resolution succeeds. This command does not install or restart an application.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
NAMES = ("requirements-dev", "requirements", "requirements-agent", "requirements-bridge", "requirements-tools", "requirements-compat")
POLICY = "--require-hashes\n--only-binary=:all:\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exclude-newer", default="2026-09-24", help="PyPI upload-date cutoff, updated explicitly with reviewed pins")
    parser.add_argument("--check", action="store_true", help="Resolve and compare; do not overwrite checked-in locks")
    args = parser.parse_args()
    uv = shutil.which("uv")
    if uv is None:
        parser.error("Install the uv resolver before regenerating requirements")
    # Do not write private index credentials or ambient resolver configuration
    # into public lockfiles. Network proxy/TLS settings remain administrator-owned.
    env = {key: value for key, value in os.environ.items() if not key.startswith(("UV_", "PIP_"))}
    with tempfile.TemporaryDirectory(prefix="codepier-lock-") as temporary:
        staging = Path(temporary)
        for name in NAMES:
            command = [uv, "--no-config", "pip", "compile", str(ROOT / (name + ".in")),
                       "--universal", "--python-version", "3.13", "--generate-hashes", "--no-build",
                       "--default-index", "https://pypi.org/simple", "--exclude-newer", args.exclude_newer,
                       "--no-annotate", "--no-header", "--output-file", str(staging / (name + ".txt"))]
            # Share transitive versions with the developer/test environment.
            # The official MCP SDK deliberately keeps its independent dependency graph.
            if name not in {"requirements-dev", "requirements-compat"}:
                command += ["--constraint", str(staging / "requirements-dev.txt")]
            subprocess.run(command, cwd=ROOT, env=env, check=True, timeout=240,
                           stdout=subprocess.DEVNULL)
        generated = {}
        for name in NAMES:
            body = (staging / (name + ".txt")).read_text(encoding="utf-8")
            header = ("# Generated by python scripts/lock_requirements.py; edit the .in inputs.\n"
                      f"# Universal Python >=3.13; PyPI upload cutoff {args.exclude_newer}.\n")
            generated[name + ".txt"] = header + POLICY + body
        changed = [name for name, body in generated.items() if (ROOT / name).read_text(encoding="utf-8") != body]
        if not args.check:
            for name in changed:
                target = ROOT / name
                descriptor, temporary_path = tempfile.mkstemp(prefix=".lock-", dir=ROOT)
                try:
                    with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
                        stream.write(generated[name]); stream.flush(); os.fsync(stream.fileno())
                    os.chmod(temporary_path, 0o644)
                    os.replace(temporary_path, target)
                finally:
                    if os.path.exists(temporary_path):
                        os.unlink(temporary_path)
        print(("Outdated: " if args.check else "Updated: ") + (", ".join(changed) or "none"))
        return 1 if args.check and changed else 0


if __name__ == "__main__":
    raise SystemExit(main())
